appname: governor
version: v0.1.0
mode: DEBUG
port: 8080
baseurl: /api
publicdir: public
templatedir: templates
max_req_size: 2M
allow_origins:
  - http://localhost:3000
  - http://localhost:3001
  - http://localhost:3030
  - http://localhost:3031
postgres:
  user: postgres
  password: admin
  dbname: governor
  host: localhost
  port: 5432
  sslmode: disable
redis:
  password: admin
  dbname: 0
  host: localhost
  port: 6379
minio:
  key_id: admin
  key_secret: adminsecret
  host: localhost
  port: 9000
  sslmode: false
nats:
  host: localhost
  port: 4222
  cluster: nss
userauth:
  issuer: governor
  secret: secret
  duration: 15m
  refresh_duration: 168h
user:
  confirm_duration: 1h
  password_reset_duration: 1h
  new_login_email: true
  password_min_size: 8
courier:
  fallback_link: localhost:8080
mail:
  host: localhost
  port: 1025
  from_address: gov@hack.com
  from_name: Hackform
  insecure: true
  buffer_size: 1024
  worker_size: 2
  conn_msg_cap: 100
post:
  archive_time: 2688h
